import type { Metadata } from "next";
import localFont from "next/font/local";
import { Container } from '@chakra-ui/react'
import "./globals.css";
import { ChakraWrapper, ApolloWrapper } from './providers'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <div className='background'>
        <img className="bg-image" src="https://www.pngarts.com/files/8/Anime-PNG-Image-Transparent.png" />
      </div>
        <ApolloWrapper>
          <ChakraWrapper>
           
              {children}
            
            </ChakraWrapper>
        </ApolloWrapper>
      </body>
    </html>
  );
}

export default RootLayout